/*!
 * File generated by platform wizard. DO NOT MODIFY
 *
 */

metaonly module Platform inherits xdc.platform.IPlatform {

    config ti.platforms.generic.Platform.Instance CPU =
        ti.platforms.generic.Platform.create("CPU", {
            clockRate:      456.0,                                       
            catalogName:    "ti.catalog.c6000",
            deviceName:     "TMS320C6748",
            customMemoryMap:
           [          
                ["DSPL2RAM", 
                     {
                        name: "DSPL2RAM",
                        base: 0x00800000,                    
                        len: 0x00040000,                    
                        space: "code/data",
                        access: "RW",
                     }
                ],
                ["SHRAM", 
                     {
                        name: "SHRAM",
                        base: 0x80000000,                    
                        len: 0x00020000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["DDR2", 
                     {
                        name: "DDR2",
                        base: 0xC0000000,                    
                        len: 0x08000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
           ],
          l2Mode: "0k",
          l1PMode: "32k",
          l1DMode: "32k",

    });
    
instance :
    
    override config string codeMemory  = "DDR2";   
    override config string dataMemory  = "DDR2";                                
    override config string stackMemory = "DSPL2RAM";

    config String l2Mode = "0k";
    config String l1PMode = "32k";
    config String l1DMode = "32k";
}
